### ISSUE TITLE
Handle long list of job status'es

### ISSUE THREAD

**Issue by thingforward** [thingforward/slyft-cli#11]
After a while there will be a lot of jobs per project. I usually want to see the status of the latest job i ran.
What about:

* When `--all` is given, show all jobs, asks user for job id; then show details for this job
* When `--all` is NOT given, do not show all jobs table; show only latest job entry in table; then show details for this job.

**Comment by sillyfellow** [comment]
it will be `[--all | --n X]  `

where all means all,

otherwise show the last `n` where default `n` is `1`
