### ISSUE TITLE
Triggering of a validation or build job should not return full job details (because it's misleading)

### ISSUE THREAD

**Issue by thingforward** [thingforward/slyft-cli#12]
Submitting a `slyft project validate` or `...build` prints out the full job detail, including a Result Status (0) and message. This is misleading.

These commands should only return a small message such as

```
Validation job 103 started, use `slyft project status` to view status details.
```

and omit the rest.

**Comment by sillyfellow** [comment]
check for 204 (success for post) and inform the user that the job has been submitted.
Otherwise show error.
