### ISSUE TITLE
Error message twice?

### ISSUE THREAD

**Issue by sillyfellow** [thingforward/slyft-cli#20]
```
We're sorry, but your registration failed due to the following errors:
* Email already in use
ERRO 001 We're very sorry, but your registration failed.
```

1. Removing the last line seems more sensible, but the first two lines may not be always there (in case the error is not an 'expected' error. (See line 256 of users.go : https://github.com/thingforward/slyft-cli/blob/master/users.go#L256 ) 

2. Change the `format` of error messages in the non-debug mode.
Remove the `ERRO 001` -- leaving the message be there.

See line 20 of main.go: https://github.com/thingforward/slyft-cli/blob/master/main.go#L20

**Comment by sillyfellow** [comment]
@aschmidt75 what shall it be?

**Comment by aschmidt75** [comment]
Let's take option 2, remove the ERRO 001 but keep both lines.

**Comment by thingforward** [comment]
that's already fixed? :-) closing this here.
