### ISSUE TITLE
parse error messages from API and pretty print

### ISSUE THREAD

**Issue by aleicher** [thingforward/slyft-cli#27]
eg. creating a second project with the same name for the same user is not allowed
The API  returns forbidden.

however, the CLI does not show this error message, hence no feedback to the user is given.

it will be nice to show the error to the user

**Comment by sillyfellow** [comment]
A lot are fixed with the change above.
The remaining will be fixed soon.

Eg. 

```
CRIT 001 {"errors":["Invalid login credentials. Please try again."]}
```
